apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deploy 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
      - name: student
        image: krushnaprakash/student:app
        ports:
        - containerPort: 8080
